# Generated by Django 5.2.6 on 2025-11-17 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calendar_app', '0001_initial'),
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendars', to='clubs.club'),
        ),
    ]
