# Generated by Django 5.2.6 on 2025-11-21 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0003_initial'),
        ('clubs', '0005_alter_club_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='is_club_mirror',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='calendar',
            name='source_club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mirror_calendars', to='clubs.club'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='is_mirror',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meeting',
            name='source_meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mirror_meetings', to='calendar_app.meeting'),
        ),
    ]
