# Generated by Django 5.2.6 on 2025-11-17 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('display_picture', models.ImageField(blank=True, upload_to='clubs/')),
                ('links', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='MergeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_1', models.BooleanField(default=False)),
                ('accepted_2', models.BooleanField(default=False)),
                ('created', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'Member'), ('organizer', 'Organizer'), ('admin', 'Admin')], max_length=50)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_club', to='clubs.club')),
            ],
        ),
    ]
