# Generated by Django 5.2.6 on 2025-11-10 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mergerequest',
            name='club_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_a_merge', to='clubs.club'),
        ),
        migrations.AddField(
            model_name='mergerequest',
            name='club_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_b_merge', to='clubs.club'),
        ),
        migrations.AddField(
            model_name='mergerequest',
            name='merged_club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clubs.club'),
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('user', 'club')},
        ),
    ]
