# Generated by Django 5.2.7 on 2025-11-19 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='club',
            name='videoEmbed',
            field=models.TextField(blank=True, default='None'),
        ),
    ]
