# Generated by Django 5.2.6 on 2025-11-20 02:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_club_summary_club_videoembed'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='lastMeetingDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, size=None),
        ),
    ]
