# Generated by Django 5.2.7 on 2025-11-20 16:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_club_lastmeetingdate_club_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25), blank=True, default=list, size=None),
        ),
    ]
