# Generated by Django 5.2.6 on 2025-11-13 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_club', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='summary',
            field=models.CharField(default='Default summary', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='club',
            name='videoEmbed',
            field=models.CharField(default='Insert video link here', max_length=400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='club',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
