# Generated by Django 5.2.6 on 2025-09-24 15:46

import django.db.models.deletion
import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('club', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document_manager', to='club.club')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to=documents.models.document_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('document_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='documents.documentmanager')),
            ],
        ),
    ]
