# Generated by Django 5.2.6 on 2025-09-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
